version: '3.8'

services:
  postgres_test:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: databaseTeste
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d databaseTeste"]
      interval: 2s
      retries: 10

    volumes:
      - pg_test_data:/var/lib/postgresql/data

volumes:
  pg_test_data:
